# Generated by Django 5.0.7 on 2024-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_password1_newuser_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='password2',
        ),
    ]
