# Generated by Django 5.0.7 on 2024-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_grade_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('الصف الأول الثانوي', 'الصف الأول الثانوي'), ('الصف الثاني الثانوي', 'الصف الثاني الثانوي'), ('الصف الثالث الثانوي', 'الصف الثالث الثانوي')], max_length=100),
        ),
    ]
