# Generated by Django 5.0.7 on 2024-08-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
    ]
