# Generated by Django 5.0.7 on 2024-09-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_newuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثي', 'انثي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, choices=[('الصف الأول الثانوي', 'الصف الأول الثانوي'), ('الصف الثاني الثانوي', 'الصف الثاني الثانوي'), ('الصف الثالث الثانوي', 'الصف الثالث الثانوي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('الإسكندرية', 'الإسكندرية'), ('الإسماعيلية', 'الإسماعيلية'), ('كفر الشيخ', 'كفر الشيخ'), ('أسوان', 'أسوان'), ('أسيوط', 'أسيوط'), ('الأقصر', 'الأقصر'), ('الوادي الجديد', 'الوادي الجديد'), ('شمال سيناء', 'شمال سيناء'), ('البحيرة', 'البحيرة'), ('بني سويف', 'بني سويف'), ('بورسعيد', 'بورسعيد'), ('البحر الأحمر', 'البحر الأحمر'), ('الجيزة', 'الجيزة'), ('الدقهلية', 'الدقهلية'), ('جنوب سيناء', 'جنوب سيناء'), ('دمياط', 'دمياط'), ('سوهاج', 'سوهاج'), ('السويس', 'السويس'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الفيوم', 'الفيوم'), ('القاهرة', 'القاهرة'), ('القليوبية', 'القليوبية'), ('قنا', 'قنا'), ('مطروح', 'مطروح'), ('المنوفية', 'المنوفية'), ('المنيا', 'المنيا')], max_length=150),
        ),
    ]
