# Generated by Django 5.0.7 on 2024-10-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
