# Generated by Django 5.0.7 on 2024-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
