# Generated by Django 5.0.7 on 2024-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usercourse_request_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
