# Generated by Django 5.0.7 on 2024-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usercourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='updated_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
