# Generated by Django 5.0.7 on 2024-10-13 19:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_sublecturedocument_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublecturevideo',
            name='video_embed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sublecturevideo',
            name='video',
            field=models.FileField(null=True, upload_to=blog.models.lecture_video_upload_to),
        ),
    ]
