# Generated by Django 5.0.7 on 2024-11-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserNotification', to='blog.notification')),
            ],
        ),
    ]
