# Generated by Django 5.0.7 on 2024-11-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_usernotificationinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
