# Generated by Django 5.0.7 on 2024-11-09 14:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_usernotificationinfo_created_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublecturequiz',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.lecture_quiz_upload_to),
        ),
        migrations.AlterField(
            model_name='sublecturevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.lecture_video_upload_to),
        ),
    ]
