# Generated by Django 5.0.7 on 2024-11-11 19:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_sublecturequiz_notes_alter_sublecturevideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublecturequiz',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.lecture_quiz_results_upload_to),
        ),
    ]
